### ISSUE TITLE
What hell?

### ISSUE THREAD

**Issue by 123ysys** [snaxgameengine/snax#3]
What the hell is this project? All three steps Setup/Generate/Builld have bugs?

**Comment by franksvm** [comment]
Whats up with the language? u sound like a spoiled brat. I do not have time to maintain this project anymore. I'm aware of the build issues caused by 3rd party updates, but I cant prioritize them atm.

**Comment by 123ysys** [comment]
> Whats up with the language? u sound like a spoiled brat. I do not have time to maintain this project anymore. I'm aware of the build issues caused by 3rd party updates, but I cant prioritize them atm.

It's not about the version of vcgpk anymore, I've asked questions in the vcgpk repository about how to upgrade and have used the latest version from 2024-01-24. Between your explanation at the first issue, did you think I wouldn't read it?
